on: 
  pull_request:
    types: [opened, synchronize]
  check_run:
    types: [rerequested]
name: Continuous Integration
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: yarn install
      uses: ./.github/actions/yarn-install
      env:
        ENLEARN_BUILD_PRIVATE_KEY: ${{ secrets.ENLEARN_BUILD_PRIVATE_KEY }}
    - name: yarn lint
      uses: docker://node:10
      with:
        entrypoint: yarn
        args: lint
    - name: yarn test
      uses: docker://node:10
      with:
        entrypoint: yarn
        args: test
